# Generated by Django 5.2 on 2025-04-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicalservice_surveyquestion_surveycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('interface', 'Доступність та зручність інтерфейсу'), ('mobile', 'Мобільна адаптація'), ('speed', 'Швидкодія та стабільність'), ('booking', 'Запис на прийом'), ('trust', 'Довіра та безпека'), ('general', 'Загальне враження')], default='general', max_length=30),
        ),
    ]
