# Generated by Django 5.2 on 2025-05-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_surveyquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
